# Generated by Django 3.2.7 on 2021-09-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresult',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Student Report', 'verbose_name_plural': 'Student Reports'},
        ),
    ]
