# Generated by Django 3.2.7 on 2021-09-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210919_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Student')]),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='term',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=1),
        ),
    ]
